##We dont give support about problems in this plugin and keep the credits.

licence: "YOUR-LICENCE"

lunar-nametags:
  staff:
    permission: "tags.staff"
    show:
      - "&8[Staff]"
      - "%player-name%"
  test1:
    permission: "tags.test1"
    show:
      - "&6[Test1]"
      - "%player-name%"
  test2:
    permission: "tags.test2"
    show:
      - "&6[Test2]"
      - "%player-name%"
  test3:
    permission: "tags.test3"
    show:
      - "&6[Test3]"
      - "%player-name%"
